import Head from "next/head";
import Image from "next/image";
import { useFormik } from "formik";
import * as Yup from "yup";

export default function Home() {
  const formik = useFormik({
    initialValues: {
      name: "",
      email: "",
      country: "United Kingdom",
      terms: "",
    },
    validationSchema: Yup.object({
      name: Yup.string().max(20, "Name must be 20 characters or less."),
    }),
    onSubmit: (values) => {
      console.log(values);
    },
  });
  console.log(formik.values);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="generated by crete next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex items-center justify-center">
        <div></div>
        <form
          action=""
          className="bg-white flex rounded-lg w-1/2 font-latoRegular"
          onSubmit={formik.handleSubmit}
        >
          <div className="flex-1 text-gray-700 p-14">
            <h1 className="text-3xl pb-2 font-latoBold">Let get started 🙌</h1>
            <p className="text-lg text-gray-500">
              Join our E-learning palform today and unlock over 500+ courses and
              digital assets ready to download.
            </p>
            <div className="mt-6">
              <div className="pb-4">
                <label
                  htmlFor="name"
                  className="block font-latoBold text-sm pb-2"
                >
                  Name
                </label>
                <input
                  type="text"
                  name="name"
                  value={formik.values.name}
                  placeholder="Enter your name"
                  className="outline-0 border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500"
                  onChange={formik.handleChange}
                />
              </div>
              <div className="pb-4">
                <label
                  htmlFor="email"
                  className="block font-latoBold text-sm pb-2"
                >
                  Name
                </label>
                <input
                  type="text"
                  name="email"
                  placeholder="Enter your email"
                  className="outline-0 border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500"
                  value={formik.values.email}
                  onChange={formik.handleChange}
                />
              </div>
              <div className="pb-4">
                <label
                  htmlFor="country"
                  className="block font-latoBold text-sm pb-2"
                >
                  Name
                </label>
                <select
                  name="country"
                  className="outline-0 border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500"
                  value={formik.values.country}
                  onChange={formik.handleChange}
                >
                  <option value="United States">United States</option>
                  <option value="United Kingdom">United Kingdom</option>
                </select>
              </div>
              <div className="pb-4">
                <label
                  htmlFor="terms"
                  className="block font-latoBold text-sm pb-2"
                >
                  Terms of service
                </label>
                <div className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    name="terms"
                    value="checked"
                    className="h-5 w-5 text-teal-500 border-2 focus:border-teal-500 focus:ring-teal-500"
                    onChange={formik.handleChange}
                  />
                  <p className="text-sm font-latoBold text-gray-500">
                    I agree to the Terms and Service that my data will be taken
                    and sold.
                  </p>
                </div>
              </div>
              <button
                type="submit"
                className="bg-teal-500 font-latoBold text-sm text-white py-3 mt-6 rounded-lg w-full"
              >
                Start learning today!
              </button>
            </div>
          </div>
          <div className="relative flex-1">
            <Image
              alt="form-learn"
              src="/form.png"
              fill
              className="object-cover rounded-lg"
            />
          </div>
        </form>
      </main>
    </>
  );
}
